Repository catebi/FreeganBot, pull requests merged in 2023-12, with the labels that each got.

#5 Task/#1
  .gitignore
  README.md
  main.py
Labels: documentation

#17 lemmatization module
  main.py
  requirements.txt
  text_processing.py
Labels: enhancement

#21 #20 lemmatize incoming messages fixes
  .gitignore
  config.dev.yaml
  config.yaml
  lemmatization.py
  main.py
  text_processing.py
Labels: enhancement

#22 #14 handle duplicate messages
  lemmatization.py
  main.py
Labels: enhancement

#26 all_photos
  main.py
Labels: enhancement

#27 Add advanced rules for message analysis for a specific group of keywords
  config.dev.yaml
  config.yaml
  main.py
Labels: enhancement, search accuracy

#29 #28 add sleep while caching
  main.py
Labels: enhancement

#33 #31 add extended logging
  main.py
Labels: logging
